name: camera_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2 # image picker   
  gallery_saver: ^2.3.2 # gallery saver
  # image_cropper: ^4.0.1  # image croper
  camera: ^0.11.0+1
  gap: ^3.0.1
  external_path: ^1.0.3
  media_scanner: ^2.1.0
  # flutter_svg: ^1.0.0  # Added this new line for svg upload

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/splash_image.png
    - assets/main_image.png
